server:
  port: 9009

spring:
  cloud:
    nacos:
      server-addr: 110.40.213.207:8848
  application:
    name: parser-provider-AnomalyDetection

rocketmq:
  name-server: 110.40.213.207:9876
  producer:
    group: parser-group

python-config:
  module-name: LogClass-master.logclass
  exp-id: 20220505