server:
  port: 9100
spring:
  application:
    name: parser-data-logDatabase
  cloud:
    nacos:
      server-addr: 110.40.213.207:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dolpdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 2@QQz2000312

rocketmq:
  name-server: 110.40.213.207:9876
  producer:
    group: read-group