server:
  port: 8001
spring:
  application:
    name: parser-consumer-logReader8001
  cloud:
    nacos:
      server-addr: 110.40.213.207:8848
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB

file:
  upload-dir: D:\MyDownloads\javaee\DOLogParser\parser-consumer-logReader8001\src\main\resources\logs\